# Site settings
title: Bleep Bloop
description: Trust the process.
show_downloads: false
show_tabs: true
google_analytics:
theme: jekyll-theme-minimal

# Project URL
permalink:  /blog/:title/

# Build settings
markdown: kramdown
